// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/earn-page/CleanWhitePro.tsx": () => import("../components/mockups/earn-page/CleanWhitePro.tsx"),
  "./components/mockups/earn-page/DarkPremium.tsx": () => import("../components/mockups/earn-page/DarkPremium.tsx"),
  "./components/mockups/earn-page/GlassMorph.tsx": () => import("../components/mockups/earn-page/GlassMorph.tsx"),
  "./components/mockups/earn-page/GoldBlack.tsx": () => import("../components/mockups/earn-page/GoldBlack.tsx"),
  "./components/mockups/earn-page/NeonCyber.tsx": () => import("../components/mockups/earn-page/NeonCyber.tsx"),
  "./components/mockups/earn-page/SunriseFintech.tsx": () => import("../components/mockups/earn-page/SunriseFintech.tsx")
};
